### YamlMime:ManagedReference
items:
- uid: SharpHoundCommonLib.LDAPConfig
  commentId: T:SharpHoundCommonLib.LDAPConfig
  id: LDAPConfig
  parent: SharpHoundCommonLib
  children:
  - SharpHoundCommonLib.LDAPConfig.DisableSigning
  - SharpHoundCommonLib.LDAPConfig.GetPort
  - SharpHoundCommonLib.LDAPConfig.Password
  - SharpHoundCommonLib.LDAPConfig.Port
  - SharpHoundCommonLib.LDAPConfig.Server
  - SharpHoundCommonLib.LDAPConfig.SSL
  - SharpHoundCommonLib.LDAPConfig.Username
  langs:
  - csharp
  - vb
  name: LDAPConfig
  nameWithType: LDAPConfig
  fullName: SharpHoundCommonLib.LDAPConfig
  type: Class
  source:
    remote:
      path: src/CommonLib/LDAPConfig.cs
      branch: master
      repo: https://github.com/BloodHoundAD/SharpHoundCommon.git
    id: LDAPConfig
    path: ../src/CommonLib/LDAPConfig.cs
    startLine: 2
  assemblies:
  - SharpHoundCommonLib
  namespace: SharpHoundCommonLib
  syntax:
    content: public class LDAPConfig
    content.vb: Public Class LDAPConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: SharpHoundCommonLib.LDAPConfig.Username
  commentId: P:SharpHoundCommonLib.LDAPConfig.Username
  id: Username
  parent: SharpHoundCommonLib.LDAPConfig
  langs:
  - csharp
  - vb
  name: Username
  nameWithType: LDAPConfig.Username
  fullName: SharpHoundCommonLib.LDAPConfig.Username
  type: Property
  source:
    remote:
      path: src/CommonLib/LDAPConfig.cs
      branch: master
      repo: https://github.com/BloodHoundAD/SharpHoundCommon.git
    id: Username
    path: ../src/CommonLib/LDAPConfig.cs
    startLine: 4
  assemblies:
  - SharpHoundCommonLib
  namespace: SharpHoundCommonLib
  syntax:
    content: public string Username { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Username As String
  overload: SharpHoundCommonLib.LDAPConfig.Username*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: SharpHoundCommonLib.LDAPConfig.Password
  commentId: P:SharpHoundCommonLib.LDAPConfig.Password
  id: Password
  parent: SharpHoundCommonLib.LDAPConfig
  langs:
  - csharp
  - vb
  name: Password
  nameWithType: LDAPConfig.Password
  fullName: SharpHoundCommonLib.LDAPConfig.Password
  type: Property
  source:
    remote:
      path: src/CommonLib/LDAPConfig.cs
      branch: master
      repo: https://github.com/BloodHoundAD/SharpHoundCommon.git
    id: Password
    path: ../src/CommonLib/LDAPConfig.cs
    startLine: 5
  assemblies:
  - SharpHoundCommonLib
  namespace: SharpHoundCommonLib
  syntax:
    content: public string Password { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Password As String
  overload: SharpHoundCommonLib.LDAPConfig.Password*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: SharpHoundCommonLib.LDAPConfig.Server
  commentId: P:SharpHoundCommonLib.LDAPConfig.Server
  id: Server
  parent: SharpHoundCommonLib.LDAPConfig
  langs:
  - csharp
  - vb
  name: Server
  nameWithType: LDAPConfig.Server
  fullName: SharpHoundCommonLib.LDAPConfig.Server
  type: Property
  source:
    remote:
      path: src/CommonLib/LDAPConfig.cs
      branch: master
      repo: https://github.com/BloodHoundAD/SharpHoundCommon.git
    id: Server
    path: ../src/CommonLib/LDAPConfig.cs
    startLine: 6
  assemblies:
  - SharpHoundCommonLib
  namespace: SharpHoundCommonLib
  syntax:
    content: public string Server { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Server As String
  overload: SharpHoundCommonLib.LDAPConfig.Server*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: SharpHoundCommonLib.LDAPConfig.Port
  commentId: P:SharpHoundCommonLib.LDAPConfig.Port
  id: Port
  parent: SharpHoundCommonLib.LDAPConfig
  langs:
  - csharp
  - vb
  name: Port
  nameWithType: LDAPConfig.Port
  fullName: SharpHoundCommonLib.LDAPConfig.Port
  type: Property
  source:
    remote:
      path: src/CommonLib/LDAPConfig.cs
      branch: master
      repo: https://github.com/BloodHoundAD/SharpHoundCommon.git
    id: Port
    path: ../src/CommonLib/LDAPConfig.cs
    startLine: 7
  assemblies:
  - SharpHoundCommonLib
  namespace: SharpHoundCommonLib
  syntax:
    content: public int Port { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Port As Integer
  overload: SharpHoundCommonLib.LDAPConfig.Port*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: SharpHoundCommonLib.LDAPConfig.SSL
  commentId: P:SharpHoundCommonLib.LDAPConfig.SSL
  id: SSL
  parent: SharpHoundCommonLib.LDAPConfig
  langs:
  - csharp
  - vb
  name: SSL
  nameWithType: LDAPConfig.SSL
  fullName: SharpHoundCommonLib.LDAPConfig.SSL
  type: Property
  source:
    remote:
      path: src/CommonLib/LDAPConfig.cs
      branch: master
      repo: https://github.com/BloodHoundAD/SharpHoundCommon.git
    id: SSL
    path: ../src/CommonLib/LDAPConfig.cs
    startLine: 8
  assemblies:
  - SharpHoundCommonLib
  namespace: SharpHoundCommonLib
  syntax:
    content: public bool SSL { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property SSL As Boolean
  overload: SharpHoundCommonLib.LDAPConfig.SSL*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: SharpHoundCommonLib.LDAPConfig.DisableSigning
  commentId: P:SharpHoundCommonLib.LDAPConfig.DisableSigning
  id: DisableSigning
  parent: SharpHoundCommonLib.LDAPConfig
  langs:
  - csharp
  - vb
  name: DisableSigning
  nameWithType: LDAPConfig.DisableSigning
  fullName: SharpHoundCommonLib.LDAPConfig.DisableSigning
  type: Property
  source:
    remote:
      path: src/CommonLib/LDAPConfig.cs
      branch: master
      repo: https://github.com/BloodHoundAD/SharpHoundCommon.git
    id: DisableSigning
    path: ../src/CommonLib/LDAPConfig.cs
    startLine: 9
  assemblies:
  - SharpHoundCommonLib
  namespace: SharpHoundCommonLib
  syntax:
    content: public bool DisableSigning { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property DisableSigning As Boolean
  overload: SharpHoundCommonLib.LDAPConfig.DisableSigning*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: SharpHoundCommonLib.LDAPConfig.GetPort
  commentId: M:SharpHoundCommonLib.LDAPConfig.GetPort
  id: GetPort
  parent: SharpHoundCommonLib.LDAPConfig
  langs:
  - csharp
  - vb
  name: GetPort()
  nameWithType: LDAPConfig.GetPort()
  fullName: SharpHoundCommonLib.LDAPConfig.GetPort()
  type: Method
  source:
    remote:
      path: src/CommonLib/LDAPConfig.cs
      branch: master
      repo: https://github.com/BloodHoundAD/SharpHoundCommon.git
    id: GetPort
    path: ../src/CommonLib/LDAPConfig.cs
    startLine: 11
  assemblies:
  - SharpHoundCommonLib
  namespace: SharpHoundCommonLib
  syntax:
    content: public int GetPort()
    return:
      type: System.Int32
    content.vb: Public Function GetPort As Integer
  overload: SharpHoundCommonLib.LDAPConfig.GetPort*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: SharpHoundCommonLib
  commentId: N:SharpHoundCommonLib
  name: SharpHoundCommonLib
  nameWithType: SharpHoundCommonLib
  fullName: SharpHoundCommonLib
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: SharpHoundCommonLib.LDAPConfig.Username*
  commentId: Overload:SharpHoundCommonLib.LDAPConfig.Username
  name: Username
  nameWithType: LDAPConfig.Username
  fullName: SharpHoundCommonLib.LDAPConfig.Username
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: SharpHoundCommonLib.LDAPConfig.Password*
  commentId: Overload:SharpHoundCommonLib.LDAPConfig.Password
  name: Password
  nameWithType: LDAPConfig.Password
  fullName: SharpHoundCommonLib.LDAPConfig.Password
- uid: SharpHoundCommonLib.LDAPConfig.Server*
  commentId: Overload:SharpHoundCommonLib.LDAPConfig.Server
  name: Server
  nameWithType: LDAPConfig.Server
  fullName: SharpHoundCommonLib.LDAPConfig.Server
- uid: SharpHoundCommonLib.LDAPConfig.Port*
  commentId: Overload:SharpHoundCommonLib.LDAPConfig.Port
  name: Port
  nameWithType: LDAPConfig.Port
  fullName: SharpHoundCommonLib.LDAPConfig.Port
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: SharpHoundCommonLib.LDAPConfig.SSL*
  commentId: Overload:SharpHoundCommonLib.LDAPConfig.SSL
  name: SSL
  nameWithType: LDAPConfig.SSL
  fullName: SharpHoundCommonLib.LDAPConfig.SSL
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: SharpHoundCommonLib.LDAPConfig.DisableSigning*
  commentId: Overload:SharpHoundCommonLib.LDAPConfig.DisableSigning
  name: DisableSigning
  nameWithType: LDAPConfig.DisableSigning
  fullName: SharpHoundCommonLib.LDAPConfig.DisableSigning
- uid: SharpHoundCommonLib.LDAPConfig.GetPort*
  commentId: Overload:SharpHoundCommonLib.LDAPConfig.GetPort
  name: GetPort
  nameWithType: LDAPConfig.GetPort
  fullName: SharpHoundCommonLib.LDAPConfig.GetPort
