name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Pack
      run: dotnet pack --no-restore -c Release --output .
    - name: Publish NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: CommonLib\CommonLib.csproj
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
        NUGET_KEY: ${{secrets.NUGET_TOKEN}}
      
